import { useState, useMemo } from "react";

const allTldsData = [
  [".aaa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".aarp","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".abb","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".abbott","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".abbvie","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".abc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".able","gTLD","Generisch (weltweit registrierbar)"],
  [".abogado","gTLD","Generisch (weltweit registrierbar)"],
  [".abudhabi","ccTLD","Abu Dhabi (VAE)"],
  [".ac","ccTLD","Ascension Island"],
  [".academy","gTLD","Generisch (weltweit registrierbar)"],
  [".accenture","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".accountant","gTLD","Generisch (weltweit registrierbar)"],
  [".accountants","gTLD","Generisch (weltweit registrierbar)"],
  [".aco","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".actor","gTLD","Generisch (weltweit registrierbar)"],
  [".ad","ccTLD","Andorra"],
  [".ads","gTLD","Generisch (weltweit registrierbar)"],
  [".adult","gTLD","Generisch (weltweit registrierbar)"],
  [".ae","ccTLD","Vereinigte Arabische Emirate"],
  [".aeg","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".aero","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".aetna","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".af","ccTLD","Afghanistan"],
  [".afl","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".africa","gTLD","Generisch (weltweit registrierbar)"],
  [".ag","ccTLD","Antigua und Barbuda"],
  [".agakhan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".agency","gTLD","Generisch (weltweit registrierbar)"],
  [".ai","ccTLD","Anguilla"],
  [".aig","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".airbus","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".airforce","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".airtel","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".akdn","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".al","ccTLD","Albanien"],
  [".alibaba","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".alipay","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".allfinanz","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".allstate","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ally","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".alsace","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".alstom","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".am","ccTLD","Armenien"],
  [".amazon","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".americanexpress","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".americanfamily","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".amex","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".amfam","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".amica","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".amsterdam","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".analytics","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".android","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".anquan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".anz","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ao","ccTLD","Angola"],
  [".aol","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".apartments","gTLD","Generisch (weltweit registrierbar)"],
  [".app","gTLD","Generisch (weltweit registrierbar)"],
  [".apple","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".aq","ccTLD","Antarktis"],
  [".aquarelle","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ar","ccTLD","Argentinien"],
  [".arab","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".aramco","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".archi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".army","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".arpa","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".art","gTLD","Generisch (weltweit registrierbar)"],
  [".arte","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".as","ccTLD","Amerikanisch-Samoa"],
  [".asda","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".asia","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".associates","gTLD","Generisch (weltweit registrierbar)"],
  [".at","ccTLD","Österreich"],
  [".athleta","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".attorney","gTLD","Generisch (weltweit registrierbar)"],
  [".au","ccTLD","Australien"],
  [".auction","gTLD","Generisch (weltweit registrierbar)"],
  [".audi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".audible","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".audio","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".auspost","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".author","gTLD","Generisch (weltweit registrierbar)"],
  [".auto","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".autos","gTLD","Generisch (weltweit registrierbar)"],
  [".aw","ccTLD","Aruba"],
  [".aws","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ax","ccTLD","Åland-Inseln"],
  [".axa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".az","ccTLD","Aserbaidschan"],
  [".azure","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ba","ccTLD","Bosnien und Herzegowina"],
  [".baby","gTLD","Generisch (weltweit registrierbar)"],
  [".baidu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".banamex","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".band","gTLD","Generisch (weltweit registrierbar)"],
  [".bank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bar","gTLD","Generisch (weltweit registrierbar)"],
  [".barcelona","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".barclaycard","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".barclays","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".barefoot","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bargains","gTLD","Generisch (weltweit registrierbar)"],
  [".baseball","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".basketball","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bauhaus","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bayern","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bb","ccTLD","Barbados"],
  [".bbc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bbt","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bbva","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bcg","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bcn","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bd","ccTLD","Bangladesch"],
  [".be","ccTLD","Belgien"],
  [".beats","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".beauty","gTLD","Generisch (weltweit registrierbar)"],
  [".beer","gTLD","Generisch (weltweit registrierbar)"],
  [".berlin","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".best","gTLD","Generisch (weltweit registrierbar)"],
  [".bestbuy","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bet","gTLD","Generisch (weltweit registrierbar)"],
  [".bf","ccTLD","Burkina Faso"],
  [".bg","ccTLD","Bulgarien"],
  [".bh","ccTLD","Bahrain"],
  [".bharti","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bi","ccTLD","Burundi"],
  [".bible","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bid","gTLD","Generisch (weltweit registrierbar)"],
  [".bike","gTLD","Generisch (weltweit registrierbar)"],
  [".bing","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bingo","gTLD","Generisch (weltweit registrierbar)"],
  [".bio","gTLD","Generisch (weltweit registrierbar)"],
  [".biz","gTLD","Generisch (weltweit registrierbar)"],
  [".bj","ccTLD","Benin"],
  [".black","gTLD","Generisch (weltweit registrierbar)"],
  [".blackfriday","gTLD","Generisch (weltweit registrierbar)"],
  [".blockbuster","gTLD","Generisch (weltweit registrierbar)"],
  [".blog","gTLD","Generisch (weltweit registrierbar)"],
  [".bloomberg","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".blue","gTLD","Generisch (weltweit registrierbar)"],
  [".bm","ccTLD","Bermuda"],
  [".bms","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bmw","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bn","ccTLD","Brunei"],
  [".bnpparibas","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bo","ccTLD","Bolivien"],
  [".boats","gTLD","Generisch (weltweit registrierbar)"],
  [".boehringer","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bofa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bom","gTLD","Generisch (weltweit registrierbar)"],
  [".bond","gTLD","Generisch (weltweit registrierbar)"],
  [".boo","gTLD","Generisch (weltweit registrierbar)"],
  [".book","gTLD","Generisch (weltweit registrierbar)"],
  [".booking","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bosch","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bostik","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".boston","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bot","gTLD","Generisch (weltweit registrierbar)"],
  [".boutique","gTLD","Generisch (weltweit registrierbar)"],
  [".box","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".br","ccTLD","Brasilien"],
  [".bradesco","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bridgestone","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".broadway","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".broker","gTLD","Generisch (weltweit registrierbar)"],
  [".brother","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".brussels","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".bs","ccTLD","Bahamas"],
  [".bt","ccTLD","Bhutan"],
  [".build","gTLD","Generisch (weltweit registrierbar)"],
  [".builders","gTLD","Generisch (weltweit registrierbar)"],
  [".business","gTLD","Generisch (weltweit registrierbar)"],
  [".buy","gTLD","Generisch (weltweit registrierbar)"],
  [".buzz","gTLD","Generisch (weltweit registrierbar)"],
  [".bv","ccTLD","Bouvetinsel"],
  [".bw","ccTLD","Botswana"],
  [".by","ccTLD","Belarus"],
  [".bz","ccTLD","Belize"],
  [".bzh","ccTLD","Bretagne (Frankreich)"],
  [".ca","ccTLD","Kanada"],
  [".cab","gTLD","Generisch (weltweit registrierbar)"],
  [".cafe","gTLD","Generisch (weltweit registrierbar)"],
  [".cal","gTLD","Generisch (weltweit registrierbar)"],
  [".call","gTLD","Generisch (weltweit registrierbar)"],
  [".calvinklein","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cam","gTLD","Generisch (weltweit registrierbar)"],
  [".camera","gTLD","Generisch (weltweit registrierbar)"],
  [".camp","gTLD","Generisch (weltweit registrierbar)"],
  [".canon","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".capetown","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".capital","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".capitalone","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".car","gTLD","Generisch (weltweit registrierbar)"],
  [".caravan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cards","gTLD","Generisch (weltweit registrierbar)"],
  [".care","gTLD","Generisch (weltweit registrierbar)"],
  [".career","gTLD","Generisch (weltweit registrierbar)"],
  [".careers","gTLD","Generisch (weltweit registrierbar)"],
  [".cars","gTLD","Generisch (weltweit registrierbar)"],
  [".casa","gTLD","Generisch (weltweit registrierbar)"],
  [".case","gTLD","Generisch (weltweit registrierbar)"],
  [".cash","gTLD","Generisch (weltweit registrierbar)"],
  [".casino","gTLD","Generisch (weltweit registrierbar)"],
  [".cat","ccTLD","Katalanische Sprache & Kultur"],
  [".catering","gTLD","Generisch (weltweit registrierbar)"],
  [".catholic","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cba","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cbn","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cbre","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cc","ccTLD","Kokosinseln"],
  [".cd","ccTLD","DR Kongo"],
  [".center","gTLD","Generisch (weltweit registrierbar)"],
  [".ceo","gTLD","Generisch (weltweit registrierbar)"],
  [".cern","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cf","ccTLD","Zentralafrikanische Republik"],
  [".cfa","gTLD","Generisch (weltweit registrierbar)"],
  [".cfd","gTLD","Generisch (weltweit registrierbar)"],
  [".cg","ccTLD","Republik Kongo"],
  [".ch","ccTLD","Schweiz"],
  [".chanel","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".channel","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".charity","gTLD","Generisch (weltweit registrierbar)"],
  [".chase","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".chat","gTLD","Generisch (weltweit registrierbar)"],
  [".cheap","gTLD","Generisch (weltweit registrierbar)"],
  [".chintai","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".christmas","gTLD","Generisch (weltweit registrierbar)"],
  [".chrome","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".church","gTLD","Generisch (weltweit registrierbar)"],
  [".ci","ccTLD","Côte d\'Ivoire"],
  [".cipriani","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".circle","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cisco","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".citadel","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".citi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".citic","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".city","gTLD","Generisch (weltweit registrierbar)"],
  [".ck","ccTLD","Cookinseln"],
  [".cl","ccTLD","Chile"],
  [".claims","gTLD","Generisch (weltweit registrierbar)"],
  [".cleaning","gTLD","Generisch (weltweit registrierbar)"],
  [".click","gTLD","Generisch (weltweit registrierbar)"],
  [".clinic","gTLD","Generisch (weltweit registrierbar)"],
  [".clinique","gTLD","Generisch (weltweit registrierbar)"],
  [".clothing","gTLD","Generisch (weltweit registrierbar)"],
  [".cloud","gTLD","Generisch (weltweit registrierbar)"],
  [".club","gTLD","Generisch (weltweit registrierbar)"],
  [".clubmed","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cm","ccTLD","Kamerun"],
  [".cn","ccTLD","China"],
  [".co","ccTLD","Kolumbien"],
  [".coach","gTLD","Generisch (weltweit registrierbar)"],
  [".codes","gTLD","Generisch (weltweit registrierbar)"],
  [".coffee","gTLD","Generisch (weltweit registrierbar)"],
  [".college","gTLD","Generisch (weltweit registrierbar)"],
  [".cologne","gTLD","Generisch (weltweit registrierbar)"],
  [".com","gTLD","Generisch (weltweit registrierbar)"],
  [".commbank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".community","gTLD","Generisch (weltweit registrierbar)"],
  [".company","gTLD","Generisch (weltweit registrierbar)"],
  [".compare","gTLD","Generisch (weltweit registrierbar)"],
  [".computer","gTLD","Generisch (weltweit registrierbar)"],
  [".comsec","gTLD","Generisch (weltweit registrierbar)"],
  [".condos","gTLD","Generisch (weltweit registrierbar)"],
  [".construction","gTLD","Generisch (weltweit registrierbar)"],
  [".consulting","gTLD","Generisch (weltweit registrierbar)"],
  [".contact","gTLD","Generisch (weltweit registrierbar)"],
  [".contractors","gTLD","Generisch (weltweit registrierbar)"],
  [".cooking","gTLD","Generisch (weltweit registrierbar)"],
  [".cool","gTLD","Generisch (weltweit registrierbar)"],
  [".coop","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".corsica","ccTLD","Korsika (Frankreich)"],
  [".country","gTLD","Generisch (weltweit registrierbar)"],
  [".coupon","gTLD","Generisch (weltweit registrierbar)"],
  [".coupons","gTLD","Generisch (weltweit registrierbar)"],
  [".courses","gTLD","Generisch (weltweit registrierbar)"],
  [".cpa","gTLD","Generisch (weltweit registrierbar)"],
  [".cr","ccTLD","Costa Rica"],
  [".credit","gTLD","Generisch (weltweit registrierbar)"],
  [".creditcard","gTLD","Generisch (weltweit registrierbar)"],
  [".creditunion","gTLD","Generisch (weltweit registrierbar)"],
  [".cricket","gTLD","Generisch (weltweit registrierbar)"],
  [".crown","gTLD","Generisch (weltweit registrierbar)"],
  [".crs","gTLD","Generisch (weltweit registrierbar)"],
  [".cruise","gTLD","Generisch (weltweit registrierbar)"],
  [".cruises","gTLD","Generisch (weltweit registrierbar)"],
  [".cu","ccTLD","Kuba"],
  [".cuisinella","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".cv","ccTLD","Cabo Verde"],
  [".cw","ccTLD","Curaçao"],
  [".cx","ccTLD","Weihnachtsinsel"],
  [".cy","ccTLD","Zypern"],
  [".cymru","ccTLD","Wales"],
  [".cyou","gTLD","Generisch (weltweit registrierbar)"],
  [".cz","ccTLD","Tschechien"],
  [".dad","gTLD","Generisch (weltweit registrierbar)"],
  [".dance","gTLD","Generisch (weltweit registrierbar)"],
  [".data","gTLD","Generisch (weltweit registrierbar)"],
  [".date","gTLD","Generisch (weltweit registrierbar)"],
  [".dating","gTLD","Generisch (weltweit registrierbar)"],
  [".datsun","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".day","gTLD","Generisch (weltweit registrierbar)"],
  [".dclk","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".dds","gTLD","Generisch (weltweit registrierbar)"],
  [".de","ccTLD","Deutschland"],
  [".deal","gTLD","Generisch (weltweit registrierbar)"],
  [".dealer","gTLD","Generisch (weltweit registrierbar)"],
  [".deals","gTLD","Generisch (weltweit registrierbar)"],
  [".degree","gTLD","Generisch (weltweit registrierbar)"],
  [".delivery","gTLD","Generisch (weltweit registrierbar)"],
  [".dell","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".deloitte","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".delta","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".democrat","gTLD","Generisch (weltweit registrierbar)"],
  [".dental","gTLD","Generisch (weltweit registrierbar)"],
  [".dentist","gTLD","Generisch (weltweit registrierbar)"],
  [".desi","gTLD","Generisch (weltweit registrierbar)"],
  [".design","gTLD","Generisch (weltweit registrierbar)"],
  [".dev","gTLD","Generisch (weltweit registrierbar)"],
  [".dhl","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".diamonds","gTLD","Generisch (weltweit registrierbar)"],
  [".diet","gTLD","Generisch (weltweit registrierbar)"],
  [".digital","gTLD","Generisch (weltweit registrierbar)"],
  [".direct","gTLD","Generisch (weltweit registrierbar)"],
  [".directory","gTLD","Generisch (weltweit registrierbar)"],
  [".discount","gTLD","Generisch (weltweit registrierbar)"],
  [".discover","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".dish","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".diy","gTLD","Generisch (weltweit registrierbar)"],
  [".dj","ccTLD","Dschibuti"],
  [".dk","ccTLD","Dänemark"],
  [".dm","ccTLD","Dominica"],
  [".dnp","gTLD","Generisch (weltweit registrierbar)"],
  [".do","ccTLD","Dominikanische Republik"],
  [".docs","gTLD","Generisch (weltweit registrierbar)"],
  [".doctor","gTLD","Generisch (weltweit registrierbar)"],
  [".dog","gTLD","Generisch (weltweit registrierbar)"],
  [".domains","gTLD","Generisch (weltweit registrierbar)"],
  [".dot","gTLD","Generisch (weltweit registrierbar)"],
  [".download","gTLD","Generisch (weltweit registrierbar)"],
  [".drive","gTLD","Generisch (weltweit registrierbar)"],
  [".dtv","gTLD","Generisch (weltweit registrierbar)"],
  [".dubai","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".dupont","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".durban","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".dvag","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".dvr","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".dz","ccTLD","Algerien"],
  [".earth","gTLD","Generisch (weltweit registrierbar)"],
  [".eat","gTLD","Generisch (weltweit registrierbar)"],
  [".ec","ccTLD","Ecuador"],
  [".eco","gTLD","Generisch (weltweit registrierbar)"],
  [".edeka","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".edu","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".education","gTLD","Generisch (weltweit registrierbar)"],
  [".ee","ccTLD","Estland"],
  [".eg","ccTLD","Ägypten"],
  [".email","gTLD","Generisch (weltweit registrierbar)"],
  [".emerck","gTLD","Generisch (weltweit registrierbar)"],
  [".energy","gTLD","Generisch (weltweit registrierbar)"],
  [".engineer","gTLD","Generisch (weltweit registrierbar)"],
  [".engineering","gTLD","Generisch (weltweit registrierbar)"],
  [".enterprises","gTLD","Generisch (weltweit registrierbar)"],
  [".epson","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".equipment","gTLD","Generisch (weltweit registrierbar)"],
  [".er","ccTLD","Eritrea"],
  [".ericsson","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".erni","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".es","ccTLD","Spanien"],
  [".esq","gTLD","Generisch (weltweit registrierbar)"],
  [".estate","gTLD","Generisch (weltweit registrierbar)"],
  [".et","ccTLD","Äthiopien"],
  [".eu","ccTLD","Europäische Union"],
  [".eurovision","gTLD","Generisch (weltweit registrierbar)"],
  [".eus","ccTLD","Baskenland"],
  [".events","gTLD","Generisch (weltweit registrierbar)"],
  [".exchange","gTLD","Generisch (weltweit registrierbar)"],
  [".expert","gTLD","Generisch (weltweit registrierbar)"],
  [".exposed","gTLD","Generisch (weltweit registrierbar)"],
  [".express","gTLD","Generisch (weltweit registrierbar)"],
  [".extraspace","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fage","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fail","gTLD","Generisch (weltweit registrierbar)"],
  [".fairwinds","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".faith","gTLD","Generisch (weltweit registrierbar)"],
  [".family","gTLD","Generisch (weltweit registrierbar)"],
  [".fan","gTLD","Generisch (weltweit registrierbar)"],
  [".fans","gTLD","Generisch (weltweit registrierbar)"],
  [".farm","gTLD","Generisch (weltweit registrierbar)"],
  [".farmers","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fashion","gTLD","Generisch (weltweit registrierbar)"],
  [".fast","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fedex","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".feedback","gTLD","Generisch (weltweit registrierbar)"],
  [".ferrari","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ferrero","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fi","ccTLD","Finnland"],
  [".fidelity","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fido","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".film","gTLD","Generisch (weltweit registrierbar)"],
  [".final","gTLD","Generisch (weltweit registrierbar)"],
  [".finance","gTLD","Generisch (weltweit registrierbar)"],
  [".financial","gTLD","Generisch (weltweit registrierbar)"],
  [".fire","gTLD","Generisch (weltweit registrierbar)"],
  [".firestone","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".firmdale","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fish","gTLD","Generisch (weltweit registrierbar)"],
  [".fishing","gTLD","Generisch (weltweit registrierbar)"],
  [".fit","gTLD","Generisch (weltweit registrierbar)"],
  [".fitness","gTLD","Generisch (weltweit registrierbar)"],
  [".fj","ccTLD","Fidschi"],
  [".fk","ccTLD","Falklandinseln"],
  [".flickr","gTLD","Generisch (weltweit registrierbar)"],
  [".flights","gTLD","Generisch (weltweit registrierbar)"],
  [".flir","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".florist","gTLD","Generisch (weltweit registrierbar)"],
  [".flowers","gTLD","Generisch (weltweit registrierbar)"],
  [".fly","gTLD","Generisch (weltweit registrierbar)"],
  [".fm","ccTLD","Föderierte Staaten von Mikronesien"],
  [".fo","ccTLD","Färöer"],
  [".foo","gTLD","Generisch (weltweit registrierbar)"],
  [".food","gTLD","Generisch (weltweit registrierbar)"],
  [".football","gTLD","Generisch (weltweit registrierbar)"],
  [".ford","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".forex","gTLD","Generisch (weltweit registrierbar)"],
  [".forsale","gTLD","Generisch (weltweit registrierbar)"],
  [".forum","gTLD","Generisch (weltweit registrierbar)"],
  [".foundation","gTLD","Generisch (weltweit registrierbar)"],
  [".fox","gTLD","Generisch (weltweit registrierbar)"],
  [".fr","ccTLD","Frankreich"],
  [".free","gTLD","Generisch (weltweit registrierbar)"],
  [".fresenius","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".frl","ccTLD","Friesland (Niederlande)"],
  [".frogans","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".frontier","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ftr","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fujitsu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".fun","gTLD","Generisch (weltweit registrierbar)"],
  [".fund","gTLD","Generisch (weltweit registrierbar)"],
  [".furniture","gTLD","Generisch (weltweit registrierbar)"],
  [".futbol","gTLD","Generisch (weltweit registrierbar)"],
  [".fyi","gTLD","Generisch (weltweit registrierbar)"],
  [".ga","ccTLD","Gabun"],
  [".gal","ccTLD","Galicien (Spanien)"],
  [".gallery","gTLD","Generisch (weltweit registrierbar)"],
  [".gallo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gallup","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".game","gTLD","Generisch (weltweit registrierbar)"],
  [".games","gTLD","Generisch (weltweit registrierbar)"],
  [".gap","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".garden","gTLD","Generisch (weltweit registrierbar)"],
  [".gay","gTLD","Generisch (weltweit registrierbar)"],
  [".gb","ccTLD","Vereinigtes Königreich"],
  [".gbiz","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gd","ccTLD","Grenada"],
  [".gdn","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ge","ccTLD","Georgien"],
  [".gea","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gent","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".genting","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".george","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gf","ccTLD","Französisch-Guayana"],
  [".gg","ccTLD","Guernsey"],
  [".ggee","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gh","ccTLD","Ghana"],
  [".gi","ccTLD","Gibraltar"],
  [".gift","gTLD","Generisch (weltweit registrierbar)"],
  [".gifts","gTLD","Generisch (weltweit registrierbar)"],
  [".gives","gTLD","Generisch (weltweit registrierbar)"],
  [".giving","gTLD","Generisch (weltweit registrierbar)"],
  [".gl","ccTLD","Grönland"],
  [".glass","gTLD","Generisch (weltweit registrierbar)"],
  [".gle","gTLD","Generisch (weltweit registrierbar)"],
  [".global","gTLD","Generisch (weltweit registrierbar)"],
  [".globo","gTLD","Generisch (weltweit registrierbar)"],
  [".gm","ccTLD","Gambia"],
  [".gmail","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gmbh","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gmo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gmx","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gn","ccTLD","Guinea"],
  [".godaddy","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gold","gTLD","Generisch (weltweit registrierbar)"],
  [".goldpoint","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".golf","gTLD","Generisch (weltweit registrierbar)"],
  [".goodyear","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".goog","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".google","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".gop","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".got","gTLD","Generisch (weltweit registrierbar)"],
  [".gov","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".gp","ccTLD","Guadeloupe"],
  [".gq","ccTLD","Äquatorialguinea"],
  [".gr","ccTLD","Griechenland"],
  [".grainger","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".graphics","gTLD","Generisch (weltweit registrierbar)"],
  [".gratis","gTLD","Generisch (weltweit registrierbar)"],
  [".green","gTLD","Generisch (weltweit registrierbar)"],
  [".gripe","gTLD","Generisch (weltweit registrierbar)"],
  [".grocery","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".group","gTLD","Generisch (weltweit registrierbar)"],
  [".gs","ccTLD","Südgeorgien u. Sandwichinseln"],
  [".gt","ccTLD","Guatemala"],
  [".gu","ccTLD","Guam"],
  [".gucci","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".guge","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".guide","gTLD","Generisch (weltweit registrierbar)"],
  [".guitars","gTLD","Generisch (weltweit registrierbar)"],
  [".guru","gTLD","Generisch (weltweit registrierbar)"],
  [".gw","ccTLD","Guinea-Bissau"],
  [".gy","ccTLD","Guyana"],
  [".hair","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hamburg","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hangout","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".haus","gTLD","Generisch (weltweit registrierbar)"],
  [".hbo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hdfc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hdfcbank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".health","gTLD","Generisch (weltweit registrierbar)"],
  [".healthcare","gTLD","Generisch (weltweit registrierbar)"],
  [".help","gTLD","Generisch (weltweit registrierbar)"],
  [".helsinki","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".here","gTLD","Generisch (weltweit registrierbar)"],
  [".hermes","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hiphop","gTLD","Generisch (weltweit registrierbar)"],
  [".hisamitsu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hitachi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hiv","gTLD","Generisch (weltweit registrierbar)"],
  [".hk","ccTLD","Hongkong"],
  [".hkt","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hm","ccTLD","Heard u. McDonald-Inseln"],
  [".hn","ccTLD","Honduras"],
  [".hockey","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".holdings","gTLD","Generisch (weltweit registrierbar)"],
  [".holiday","gTLD","Generisch (weltweit registrierbar)"],
  [".homedepot","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".homegoods","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".homes","gTLD","Generisch (weltweit registrierbar)"],
  [".homesense","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".honda","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".horse","gTLD","Generisch (weltweit registrierbar)"],
  [".hospital","gTLD","Generisch (weltweit registrierbar)"],
  [".host","gTLD","Generisch (weltweit registrierbar)"],
  [".hosting","gTLD","Generisch (weltweit registrierbar)"],
  [".hot","gTLD","Generisch (weltweit registrierbar)"],
  [".hotels","gTLD","Generisch (weltweit registrierbar)"],
  [".hotmail","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".house","gTLD","Generisch (weltweit registrierbar)"],
  [".how","gTLD","Generisch (weltweit registrierbar)"],
  [".hr","ccTLD","Kroatien"],
  [".hsbc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ht","ccTLD","Haiti"],
  [".hu","ccTLD","Ungarn"],
  [".hughes","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hyatt","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".hyundai","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ibm","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".icbc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ice","gTLD","Generisch (weltweit registrierbar)"],
  [".icu","gTLD","Generisch (weltweit registrierbar)"],
  [".id","ccTLD","Indonesien"],
  [".ie","ccTLD","Irland"],
  [".ieee","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ifm","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ikano","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".il","ccTLD","Israel"],
  [".im","ccTLD","Isle of Man"],
  [".imamat","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".imdb","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".immo","gTLD","Generisch (weltweit registrierbar)"],
  [".immobilien","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".in","ccTLD","Indien"],
  [".inc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".industries","gTLD","Generisch (weltweit registrierbar)"],
  [".infiniti","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".info","gTLD","Generisch (weltweit registrierbar)"],
  [".ing","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ink","gTLD","Generisch (weltweit registrierbar)"],
  [".institute","gTLD","Generisch (weltweit registrierbar)"],
  [".insurance","gTLD","Generisch (weltweit registrierbar)"],
  [".insure","gTLD","Generisch (weltweit registrierbar)"],
  [".int","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".international","gTLD","Generisch (weltweit registrierbar)"],
  [".intuit","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".investments","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".io","ccTLD","Brit. Ind. Ozean Terr."],
  [".ipiranga","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".iq","ccTLD","Irak"],
  [".ir","ccTLD","Iran"],
  [".irish","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".is","ccTLD","Island"],
  [".ismaili","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ist","gTLD","Generisch (weltweit registrierbar)"],
  [".istanbul","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".it","ccTLD","Italien"],
  [".itau","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".itv","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jaguar","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".java","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jcb","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".je","ccTLD","Jersey"],
  [".jeep","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jetzt","gTLD","Generisch (weltweit registrierbar)"],
  [".jewelry","gTLD","Generisch (weltweit registrierbar)"],
  [".jio","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jll","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jm","ccTLD","Jamaika"],
  [".jmp","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jnj","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jo","ccTLD","Jordanien"],
  [".jobs","gTLD","Generisch (weltweit registrierbar)"],
  [".joburg","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jot","gTLD","Generisch (weltweit registrierbar)"],
  [".joy","gTLD","Generisch (weltweit registrierbar)"],
  [".jp","ccTLD","Japan"],
  [".jpmorgan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".jprs","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".juegos","gTLD","Generisch (weltweit registrierbar)"],
  [".juniper","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kaufen","gTLD","Generisch (weltweit registrierbar)"],
  [".kddi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ke","ccTLD","Kenia"],
  [".kerryhotels","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kerryproperties","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kfh","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kg","ccTLD","Kirgisistan"],
  [".kh","ccTLD","Kambodscha"],
  [".ki","ccTLD","Kiribati"],
  [".kia","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kids","gTLD","Generisch (weltweit registrierbar)"],
  [".kim","gTLD","Generisch (weltweit registrierbar)"],
  [".kindle","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kitchen","gTLD","Generisch (weltweit registrierbar)"],
  [".kiwi","gTLD","Generisch (weltweit registrierbar)"],
  [".km","ccTLD","Komoren"],
  [".kn","ccTLD","St. Kitts und Nevis"],
  [".koeln","ccTLD","Köln (Deutschland)"],
  [".komatsu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kosher","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kp","ccTLD","Nordkorea"],
  [".kpmg","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kpn","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kr","ccTLD","Südkorea"],
  [".krd","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kred","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kuokgroup","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kw","ccTLD","Kuwait"],
  [".ky","ccTLD","Kaimaninseln"],
  [".kyoto","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".kz","ccTLD","Kasachstan"],
  [".la","ccTLD","Laos"],
  [".lacaixa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lamborghini","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lamer","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".land","gTLD","Generisch (weltweit registrierbar)"],
  [".landrover","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lanxess","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lasalle","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lat","gTLD","Generisch (weltweit registrierbar)"],
  [".latino","gTLD","Generisch (weltweit registrierbar)"],
  [".latrobe","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".law","gTLD","Generisch (weltweit registrierbar)"],
  [".lawyer","gTLD","Generisch (weltweit registrierbar)"],
  [".lb","ccTLD","Libanon"],
  [".lc","ccTLD","St. Lucia"],
  [".lds","gTLD","Generisch (weltweit registrierbar)"],
  [".lease","gTLD","Generisch (weltweit registrierbar)"],
  [".leclerc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lefrak","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".legal","gTLD","Generisch (weltweit registrierbar)"],
  [".lego","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lexus","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lgbt","gTLD","Generisch (weltweit registrierbar)"],
  [".li","ccTLD","Liechtenstein"],
  [".lidl","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".life","gTLD","Generisch (weltweit registrierbar)"],
  [".lifeinsurance","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lifestyle","gTLD","Generisch (weltweit registrierbar)"],
  [".lighting","gTLD","Generisch (weltweit registrierbar)"],
  [".like","gTLD","Generisch (weltweit registrierbar)"],
  [".lilly","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".limited","gTLD","Generisch (weltweit registrierbar)"],
  [".limo","gTLD","Generisch (weltweit registrierbar)"],
  [".lincoln","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".link","gTLD","Generisch (weltweit registrierbar)"],
  [".live","gTLD","Generisch (weltweit registrierbar)"],
  [".living","gTLD","Generisch (weltweit registrierbar)"],
  [".lk","ccTLD","Sri Lanka"],
  [".llc","gTLD","Generisch (weltweit registrierbar)"],
  [".llp","gTLD","Generisch (weltweit registrierbar)"],
  [".loan","gTLD","Generisch (weltweit registrierbar)"],
  [".loans","gTLD","Generisch (weltweit registrierbar)"],
  [".locker","gTLD","Generisch (weltweit registrierbar)"],
  [".locus","gTLD","Generisch (weltweit registrierbar)"],
  [".lol","gTLD","Generisch (weltweit registrierbar)"],
  [".london","ccTLD","London (UK)"],
  [".lotte","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lotto","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".love","gTLD","Generisch (weltweit registrierbar)"],
  [".lpl","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lplfinancial","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".lr","ccTLD","Liberia"],
  [".ls","ccTLD","Lesotho"],
  [".lt","ccTLD","Litauen"],
  [".ltd","gTLD","Generisch (weltweit registrierbar)"],
  [".ltda","gTLD","Generisch (weltweit registrierbar)"],
  [".lu","ccTLD","Luxemburg"],
  [".lundbeck","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".luxe","gTLD","Generisch (weltweit registrierbar)"],
  [".luxury","gTLD","Generisch (weltweit registrierbar)"],
  [".lv","ccTLD","Lettland"],
  [".ly","ccTLD","Libyen"],
  [".ma","ccTLD","Marokko"],
  [".madrid","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".maif","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".maison","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".makeup","gTLD","Generisch (weltweit registrierbar)"],
  [".man","gTLD","Generisch (weltweit registrierbar)"],
  [".management","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mango","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".map","gTLD","Generisch (weltweit registrierbar)"],
  [".market","gTLD","Generisch (weltweit registrierbar)"],
  [".marketing","gTLD","Generisch (weltweit registrierbar)"],
  [".markets","gTLD","Generisch (weltweit registrierbar)"],
  [".marriott","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".marshalls","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mattel","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mba","gTLD","Generisch (weltweit registrierbar)"],
  [".mc","ccTLD","Monaco"],
  [".mckinsey","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".md","ccTLD","Moldau"],
  [".me","ccTLD","Montenegro"],
  [".med","gTLD","Generisch (weltweit registrierbar)"],
  [".media","gTLD","Generisch (weltweit registrierbar)"],
  [".meet","gTLD","Generisch (weltweit registrierbar)"],
  [".melbourne","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".meme","gTLD","Generisch (weltweit registrierbar)"],
  [".memorial","gTLD","Generisch (weltweit registrierbar)"],
  [".men","gTLD","Generisch (weltweit registrierbar)"],
  [".menu","gTLD","Generisch (weltweit registrierbar)"],
  [".merck","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".merckmsd","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mg","ccTLD","Madagaskar"],
  [".mh","ccTLD","Marshallinseln"],
  [".miami","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".microsoft","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mil","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".mini","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mint","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mit","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mitsubishi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mk","ccTLD","Nordmazedonien"],
  [".ml","ccTLD","Mali"],
  [".mlb","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mls","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mm","ccTLD","Myanmar"],
  [".mma","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mn","ccTLD","Mongolei"],
  [".mo","ccTLD","Macao"],
  [".mobi","gTLD","Generisch (weltweit registrierbar)"],
  [".mobile","gTLD","Generisch (weltweit registrierbar)"],
  [".moda","gTLD","Generisch (weltweit registrierbar)"],
  [".moe","gTLD","Generisch (weltweit registrierbar)"],
  [".moi","gTLD","Generisch (weltweit registrierbar)"],
  [".mom","gTLD","Generisch (weltweit registrierbar)"],
  [".monash","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".money","gTLD","Generisch (weltweit registrierbar)"],
  [".monster","gTLD","Generisch (weltweit registrierbar)"],
  [".mormon","gTLD","Generisch (weltweit registrierbar)"],
  [".mortgage","gTLD","Generisch (weltweit registrierbar)"],
  [".moscow","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".moto","gTLD","Generisch (weltweit registrierbar)"],
  [".motorcycles","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".mov","gTLD","Generisch (weltweit registrierbar)"],
  [".movie","gTLD","Generisch (weltweit registrierbar)"],
  [".mp","ccTLD","Nördliche Marianen"],
  [".mq","ccTLD","Martinique"],
  [".mr","ccTLD","Mauretanien"],
  [".ms","ccTLD","Montserrat"],
  [".msd","gTLD","Generisch (weltweit registrierbar)"],
  [".mt","ccTLD","Malta"],
  [".mtn","gTLD","Generisch (weltweit registrierbar)"],
  [".mtr","gTLD","Generisch (weltweit registrierbar)"],
  [".mu","ccTLD","Mauritius"],
  [".museum","Infra/sTLD","Globale Infrastruktur / Gesponsertes TLD"],
  [".music","gTLD","Generisch (weltweit registrierbar)"],
  [".mv","ccTLD","Malediven"],
  [".mw","ccTLD","Malawi"],
  [".mx","ccTLD","Mexiko"],
  [".my","ccTLD","Malaysia"],
  [".mz","ccTLD","Mosambik"],
  [".na","ccTLD","Namibia"],
  [".nab","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nagoya","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".name","gTLD","Generisch (weltweit registrierbar)"],
  [".navy","gTLD","Generisch (weltweit registrierbar)"],
  [".nba","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nc","ccTLD","Neukaledonien"],
  [".ne","ccTLD","Niger"],
  [".nec","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".net","gTLD","Generisch (weltweit registrierbar)"],
  [".netbank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".netflix","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".network","gTLD","Generisch (weltweit registrierbar)"],
  [".neustar","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".new","gTLD","Generisch (weltweit registrierbar)"],
  [".news","gTLD","Generisch (weltweit registrierbar)"],
  [".next","gTLD","Generisch (weltweit registrierbar)"],
  [".nextdirect","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nexus","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nf","ccTLD","Norfolkinsel"],
  [".nfl","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ng","ccTLD","Nigeria"],
  [".ngo","gTLD","Generisch (weltweit registrierbar)"],
  [".nhk","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ni","ccTLD","Nicaragua"],
  [".nico","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nike","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nikon","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ninja","gTLD","Generisch (weltweit registrierbar)"],
  [".nissan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nissay","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nl","ccTLD","Niederlande"],
  [".no","ccTLD","Norwegen"],
  [".nokia","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".norton","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".now","gTLD","Generisch (weltweit registrierbar)"],
  [".nowruz","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nowtv","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".np","ccTLD","Nepal"],
  [".nr","ccTLD","Nauru"],
  [".nra","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nrw","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ntt","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".nu","ccTLD","Niue"],
  [".nyc","ccTLD","New York City (USA)"],
  [".nz","ccTLD","Neuseeland"],
  [".obi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".observer","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".office","gTLD","Generisch (weltweit registrierbar)"],
  [".okinawa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".olayan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".olayangroup","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ollo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".om","ccTLD","Oman"],
  [".omega","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".one","gTLD","Generisch (weltweit registrierbar)"],
  [".ong","gTLD","Generisch (weltweit registrierbar)"],
  [".onl","gTLD","Generisch (weltweit registrierbar)"],
  [".online","gTLD","Generisch (weltweit registrierbar)"],
  [".ooo","gTLD","Generisch (weltweit registrierbar)"],
  [".open","gTLD","Generisch (weltweit registrierbar)"],
  [".oracle","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".orange","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".org","gTLD","Generisch (weltweit registrierbar)"],
  [".organic","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".origins","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".osaka","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".otsuka","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ott","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ovh","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".pa","ccTLD","Panama"],
  [".page","gTLD","Generisch (weltweit registrierbar)"],
  [".panasonic","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".paris","ccTLD","Paris (Frankreich)"],
  [".pars","gTLD","Generisch (weltweit registrierbar)"],
  [".partners","gTLD","Generisch (weltweit registrierbar)"],
  [".parts","gTLD","Generisch (weltweit registrierbar)"],
  [".party","gTLD","Generisch (weltweit registrierbar)"],
  [".pay","gTLD","Generisch (weltweit registrierbar)"],
  [".pccw","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".pe","ccTLD","Peru"],
  [".pet","gTLD","Generisch (weltweit registrierbar)"],
  [".pf","ccTLD","Französisch-Polynesien"],
  [".pfizer","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".pg","ccTLD","Papua-Neuguinea"],
  [".ph","ccTLD","Philippinen"],
  [".pharmacy","gTLD","Generisch (weltweit registrierbar)"],
  [".phd","gTLD","Generisch (weltweit registrierbar)"],
  [".philips","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".phone","gTLD","Generisch (weltweit registrierbar)"],
  [".photo","gTLD","Generisch (weltweit registrierbar)"],
  [".photography","gTLD","Generisch (weltweit registrierbar)"],
  [".photos","gTLD","Generisch (weltweit registrierbar)"],
  [".physio","gTLD","Generisch (weltweit registrierbar)"],
  [".pics","gTLD","Generisch (weltweit registrierbar)"],
  [".pictet","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".pictures","gTLD","Generisch (weltweit registrierbar)"],
  [".pid","gTLD","Generisch (weltweit registrierbar)"],
  [".pin","gTLD","Generisch (weltweit registrierbar)"],
  [".ping","gTLD","Generisch (weltweit registrierbar)"],
  [".pink","gTLD","Generisch (weltweit registrierbar)"],
  [".pioneer","gTLD","Generisch (weltweit registrierbar)"],
  [".pizza","gTLD","Generisch (weltweit registrierbar)"],
  [".pk","ccTLD","Pakistan"],
  [".pl","ccTLD","Polen"],
  [".place","gTLD","Generisch (weltweit registrierbar)"],
  [".play","gTLD","Generisch (weltweit registrierbar)"],
  [".playstation","gTLD","Generisch (weltweit registrierbar)"],
  [".plumbing","gTLD","Generisch (weltweit registrierbar)"],
  [".plus","gTLD","Generisch (weltweit registrierbar)"],
  [".pm","ccTLD","St-Pierre und Miquelon"],
  [".pn","ccTLD","Pitcairn-Inseln"],
  [".pnc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".pohl","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".poker","gTLD","Generisch (weltweit registrierbar)"],
  [".politie","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".porn","gTLD","Generisch (weltweit registrierbar)"],
  [".post","gTLD","Generisch (weltweit registrierbar)"],
  [".pr","ccTLD","Puerto Rico"],
  [".praxi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".press","gTLD","Generisch (weltweit registrierbar)"],
  [".prime","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".pro","gTLD","Generisch (weltweit registrierbar)"],
  [".prod","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".productions","gTLD","Generisch (weltweit registrierbar)"],
  [".prof","gTLD","Generisch (weltweit registrierbar)"],
  [".progressive","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".promo","gTLD","Generisch (weltweit registrierbar)"],
  [".properties","gTLD","Generisch (weltweit registrierbar)"],
  [".property","gTLD","Generisch (weltweit registrierbar)"],
  [".protection","gTLD","Generisch (weltweit registrierbar)"],
  [".pru","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".prudential","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ps","ccTLD","Palästina"],
  [".pt","ccTLD","Portugal"],
  [".pub","gTLD","Generisch (weltweit registrierbar)"],
  [".pw","ccTLD","Palau"],
  [".pwc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".py","ccTLD","Paraguay"],
  [".qa","ccTLD","Katar"],
  [".qpon","gTLD","Generisch (weltweit registrierbar)"],
  [".quebec","ccTLD","Québec (Kanada)"],
  [".quest","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".racing","gTLD","Generisch (weltweit registrierbar)"],
  [".radio","gTLD","Generisch (weltweit registrierbar)"],
  [".re","ccTLD","Réunion"],
  [".read","gTLD","Generisch (weltweit registrierbar)"],
  [".realestate","gTLD","Generisch (weltweit registrierbar)"],
  [".realtor","gTLD","Generisch (weltweit registrierbar)"],
  [".realty","gTLD","Generisch (weltweit registrierbar)"],
  [".recipes","gTLD","Generisch (weltweit registrierbar)"],
  [".red","gTLD","Generisch (weltweit registrierbar)"],
  [".redumbrella","gTLD","Generisch (weltweit registrierbar)"],
  [".rehab","gTLD","Generisch (weltweit registrierbar)"],
  [".reise","gTLD","Generisch (weltweit registrierbar)"],
  [".reisen","gTLD","Generisch (weltweit registrierbar)"],
  [".reit","gTLD","Generisch (weltweit registrierbar)"],
  [".reliance","gTLD","Generisch (weltweit registrierbar)"],
  [".ren","gTLD","Generisch (weltweit registrierbar)"],
  [".rent","gTLD","Generisch (weltweit registrierbar)"],
  [".rentals","gTLD","Generisch (weltweit registrierbar)"],
  [".repair","gTLD","Generisch (weltweit registrierbar)"],
  [".report","gTLD","Generisch (weltweit registrierbar)"],
  [".republican","gTLD","Generisch (weltweit registrierbar)"],
  [".rest","gTLD","Generisch (weltweit registrierbar)"],
  [".restaurant","gTLD","Generisch (weltweit registrierbar)"],
  [".review","gTLD","Generisch (weltweit registrierbar)"],
  [".reviews","gTLD","Generisch (weltweit registrierbar)"],
  [".rexroth","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".rich","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".richardli","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ricoh","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ril","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".rio","gTLD","Generisch (weltweit registrierbar)"],
  [".rip","gTLD","Generisch (weltweit registrierbar)"],
  [".ro","ccTLD","Rumänien"],
  [".rocks","gTLD","Generisch (weltweit registrierbar)"],
  [".rodeo","gTLD","Generisch (weltweit registrierbar)"],
  [".rogers","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".room","gTLD","Generisch (weltweit registrierbar)"],
  [".rs","ccTLD","Serbien"],
  [".rsvp","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ru","ccTLD","Russland"],
  [".rugby","gTLD","Generisch (weltweit registrierbar)"],
  [".ruhr","ccTLD","Ruhrgebiet (Deutschland)"],
  [".run","gTLD","Generisch (weltweit registrierbar)"],
  [".rw","ccTLD","Ruanda"],
  [".rwe","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ryukyu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sa","ccTLD","Saudi-Arabien"],
  [".saarland","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".safe","gTLD","Generisch (weltweit registrierbar)"],
  [".safety","gTLD","Generisch (weltweit registrierbar)"],
  [".sakura","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sale","gTLD","Generisch (weltweit registrierbar)"],
  [".salon","gTLD","Generisch (weltweit registrierbar)"],
  [".samsclub","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".samsung","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sandvik","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sandvikcoromant","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sanofi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sap","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sarl","gTLD","Generisch (weltweit registrierbar)"],
  [".sas","gTLD","Generisch (weltweit registrierbar)"],
  [".save","gTLD","Generisch (weltweit registrierbar)"],
  [".saxo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sb","ccTLD","Salomonen"],
  [".sbi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sbs","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sc","ccTLD","Seychellen"],
  [".scb","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".schaeffler","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".schmidt","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".scholarships","gTLD","Generisch (weltweit registrierbar)"],
  [".school","gTLD","Generisch (weltweit registrierbar)"],
  [".schule","gTLD","Generisch (weltweit registrierbar)"],
  [".schwarz","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".science","gTLD","Generisch (weltweit registrierbar)"],
  [".scot","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sd","ccTLD","Sudan"],
  [".se","ccTLD","Schweden"],
  [".search","gTLD","Generisch (weltweit registrierbar)"],
  [".seat","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".secure","gTLD","Generisch (weltweit registrierbar)"],
  [".security","gTLD","Generisch (weltweit registrierbar)"],
  [".seek","gTLD","Generisch (weltweit registrierbar)"],
  [".select","gTLD","Generisch (weltweit registrierbar)"],
  [".sener","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".services","gTLD","Generisch (weltweit registrierbar)"],
  [".seven","gTLD","Generisch (weltweit registrierbar)"],
  [".sew","gTLD","Generisch (weltweit registrierbar)"],
  [".sex","gTLD","Generisch (weltweit registrierbar)"],
  [".sexy","gTLD","Generisch (weltweit registrierbar)"],
  [".sfr","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sg","ccTLD","Singapur"],
  [".sh","ccTLD","St. Helena"],
  [".shangrila","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sharp","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".shell","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".shia","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".shiksha","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".shoes","gTLD","Generisch (weltweit registrierbar)"],
  [".shop","gTLD","Generisch (weltweit registrierbar)"],
  [".shopping","gTLD","Generisch (weltweit registrierbar)"],
  [".shouji","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".show","gTLD","Generisch (weltweit registrierbar)"],
  [".si","ccTLD","Slowenien"],
  [".silk","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sina","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".singles","gTLD","Generisch (weltweit registrierbar)"],
  [".site","gTLD","Generisch (weltweit registrierbar)"],
  [".sj","ccTLD","Svalbard und Jan Mayen"],
  [".sk","ccTLD","Slowakei"],
  [".ski","gTLD","Generisch (weltweit registrierbar)"],
  [".skin","gTLD","Generisch (weltweit registrierbar)"],
  [".sky","gTLD","Generisch (weltweit registrierbar)"],
  [".skype","gTLD","Generisch (weltweit registrierbar)"],
  [".sl","ccTLD","Sierra Leone"],
  [".sling","gTLD","Generisch (weltweit registrierbar)"],
  [".sm","ccTLD","San Marino"],
  [".smart","gTLD","Generisch (weltweit registrierbar)"],
  [".smile","gTLD","Generisch (weltweit registrierbar)"],
  [".sn","ccTLD","Senegal"],
  [".sncf","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".so","ccTLD","Somalia"],
  [".soccer","gTLD","Generisch (weltweit registrierbar)"],
  [".social","gTLD","Generisch (weltweit registrierbar)"],
  [".softbank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".software","gTLD","Generisch (weltweit registrierbar)"],
  [".sohu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".solar","gTLD","Generisch (weltweit registrierbar)"],
  [".solutions","gTLD","Generisch (weltweit registrierbar)"],
  [".song","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sony","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".soy","gTLD","Generisch (weltweit registrierbar)"],
  [".spa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".space","gTLD","Generisch (weltweit registrierbar)"],
  [".sport","gTLD","Generisch (weltweit registrierbar)"],
  [".spot","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sr","ccTLD","Surinam"],
  [".srl","gTLD","Generisch (weltweit registrierbar)"],
  [".ss","ccTLD","Südsudan"],
  [".st","ccTLD","São Tomé und Príncipe"],
  [".stada","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".staples","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".star","gTLD","Generisch (weltweit registrierbar)"],
  [".statebank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".statefarm","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".stc","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".stcgroup","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".stockholm","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".storage","gTLD","Generisch (weltweit registrierbar)"],
  [".store","gTLD","Generisch (weltweit registrierbar)"],
  [".stream","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".studio","gTLD","Generisch (weltweit registrierbar)"],
  [".study","gTLD","Generisch (weltweit registrierbar)"],
  [".style","gTLD","Generisch (weltweit registrierbar)"],
  [".su","ccTLD","Sowjetunion (historisch)"],
  [".sucks","gTLD","Generisch (weltweit registrierbar)"],
  [".supplies","gTLD","Generisch (weltweit registrierbar)"],
  [".supply","gTLD","Generisch (weltweit registrierbar)"],
  [".support","gTLD","Generisch (weltweit registrierbar)"],
  [".surf","gTLD","Generisch (weltweit registrierbar)"],
  [".surgery","gTLD","Generisch (weltweit registrierbar)"],
  [".suzuki","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sv","ccTLD","El Salvador"],
  [".swatch","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".swiss","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".sx","ccTLD","Sint Maarten"],
  [".sy","ccTLD","Syrien"],
  [".sydney","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".systems","gTLD","Generisch (weltweit registrierbar)"],
  [".sz","ccTLD","Eswatini"],
  [".tab","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".taipei","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".talk","gTLD","Generisch (weltweit registrierbar)"],
  [".taobao","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".target","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tatamotors","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tatar","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tattoo","gTLD","Generisch (weltweit registrierbar)"],
  [".tax","gTLD","Generisch (weltweit registrierbar)"],
  [".taxi","gTLD","Generisch (weltweit registrierbar)"],
  [".tc","ccTLD","Turks- und Caicosinseln"],
  [".tci","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".td","ccTLD","Tschad"],
  [".tdk","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".team","gTLD","Generisch (weltweit registrierbar)"],
  [".tech","gTLD","Generisch (weltweit registrierbar)"],
  [".technology","gTLD","Generisch (weltweit registrierbar)"],
  [".tel","gTLD","Generisch (weltweit registrierbar)"],
  [".temasek","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tennis","gTLD","Generisch (weltweit registrierbar)"],
  [".teva","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tf","ccTLD","Frz. Südterritorien"],
  [".tg","ccTLD","Togo"],
  [".th","ccTLD","Thailand"],
  [".thd","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".theater","gTLD","Generisch (weltweit registrierbar)"],
  [".theatre","gTLD","Generisch (weltweit registrierbar)"],
  [".tiaa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tickets","gTLD","Generisch (weltweit registrierbar)"],
  [".tienda","gTLD","Generisch (weltweit registrierbar)"],
  [".tips","gTLD","Generisch (weltweit registrierbar)"],
  [".tires","gTLD","Generisch (weltweit registrierbar)"],
  [".tirol","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tj","ccTLD","Tadschikistan"],
  [".tjmaxx","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tjx","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tk","ccTLD","Tokelau"],
  [".tkmaxx","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tl","ccTLD","Osttimor"],
  [".tm","ccTLD","Turkmenistan"],
  [".tmall","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tn","ccTLD","Tunesien"],
  [".to","ccTLD","Tonga"],
  [".today","gTLD","Generisch (weltweit registrierbar)"],
  [".tokyo","ccTLD","Tokio (Japan)"],
  [".tools","gTLD","Generisch (weltweit registrierbar)"],
  [".top","gTLD","Generisch (weltweit registrierbar)"],
  [".toray","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".toshiba","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".total","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tours","gTLD","Generisch (weltweit registrierbar)"],
  [".town","gTLD","Generisch (weltweit registrierbar)"],
  [".toyota","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".toys","gTLD","Generisch (weltweit registrierbar)"],
  [".tr","ccTLD","Türkei"],
  [".trade","gTLD","Generisch (weltweit registrierbar)"],
  [".trading","gTLD","Generisch (weltweit registrierbar)"],
  [".training","gTLD","Generisch (weltweit registrierbar)"],
  [".travel","gTLD","Generisch (weltweit registrierbar)"],
  [".travelers","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".travelersinsurance","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".trust","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".trv","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tt","ccTLD","Trinidad und Tobago"],
  [".tube","gTLD","Generisch (weltweit registrierbar)"],
  [".tui","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tunes","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tushu","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tv","ccTLD","Tuvalu"],
  [".tvs","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".tw","ccTLD","Taiwan"],
  [".tz","ccTLD","Tansania"],
  [".ua","ccTLD","Ukraine"],
  [".ubank","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ubs","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ug","ccTLD","Uganda"],
  [".uk","ccTLD","Vereinigtes Königreich"],
  [".unicom","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".university","gTLD","Generisch (weltweit registrierbar)"],
  [".uno","gTLD","Generisch (weltweit registrierbar)"],
  [".uol","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ups","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".us","ccTLD","USA"],
  [".uy","ccTLD","Uruguay"],
  [".uz","ccTLD","Usbekistan"],
  [".va","ccTLD","Vatikanstadt"],
  [".vacations","gTLD","Generisch (weltweit registrierbar)"],
  [".vana","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vanguard","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vc","ccTLD","St. Vincent und Grenadinen"],
  [".ve","ccTLD","Venezuela"],
  [".vegas","gTLD","Generisch (weltweit registrierbar)"],
  [".ventures","gTLD","Generisch (weltweit registrierbar)"],
  [".verisign","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".versicherung","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vet","gTLD","Generisch (weltweit registrierbar)"],
  [".vg","ccTLD","Brit. Jungferninseln"],
  [".vi","ccTLD","Amerikanische Jungferninseln"],
  [".viajes","gTLD","Generisch (weltweit registrierbar)"],
  [".video","gTLD","Generisch (weltweit registrierbar)"],
  [".vig","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".viking","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".villas","gTLD","Generisch (weltweit registrierbar)"],
  [".vin","gTLD","Generisch (weltweit registrierbar)"],
  [".vip","gTLD","Generisch (weltweit registrierbar)"],
  [".virgin","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".visa","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vision","gTLD","Generisch (weltweit registrierbar)"],
  [".viva","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vivo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vlaanderen","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vn","ccTLD","Vietnam"],
  [".vodka","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".volvo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".vote","gTLD","Generisch (weltweit registrierbar)"],
  [".voting","gTLD","Generisch (weltweit registrierbar)"],
  [".voto","gTLD","Generisch (weltweit registrierbar)"],
  [".voyage","gTLD","Generisch (weltweit registrierbar)"],
  [".vu","ccTLD","Vanuatu"],
  [".wales","ccTLD","Wales"],
  [".walmart","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".walter","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".wang","gTLD","Generisch (weltweit registrierbar)"],
  [".wanggou","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".watch","gTLD","Generisch (weltweit registrierbar)"],
  [".watches","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".weather","gTLD","Generisch (weltweit registrierbar)"],
  [".weatherchannel","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".webcam","gTLD","Generisch (weltweit registrierbar)"],
  [".weber","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".website","gTLD","Generisch (weltweit registrierbar)"],
  [".wed","gTLD","Generisch (weltweit registrierbar)"],
  [".wedding","gTLD","Generisch (weltweit registrierbar)"],
  [".weibo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".weir","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".wf","ccTLD","Wallis und Futuna"],
  [".whoswho","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".wien","ccTLD","Wien (Österreich)"],
  [".wiki","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".williamhill","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".win","gTLD","Generisch (weltweit registrierbar)"],
  [".windows","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".wine","gTLD","Generisch (weltweit registrierbar)"],
  [".winners","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".wme","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".woodside","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".work","gTLD","Generisch (weltweit registrierbar)"],
  [".works","gTLD","Generisch (weltweit registrierbar)"],
  [".world","gTLD","Generisch (weltweit registrierbar)"],
  [".wow","gTLD","Generisch (weltweit registrierbar)"],
  [".ws","ccTLD","Samoa"],
  [".wtc","gTLD","Generisch (weltweit registrierbar)"],
  [".wtf","gTLD","Generisch (weltweit registrierbar)"],
  [".xbox","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".xerox","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".xihuan","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".xin","gTLD","Generisch (weltweit registrierbar)"],
  [".xxx","gTLD","Generisch (weltweit registrierbar)"],
  [".xyz","gTLD","Generisch (weltweit registrierbar)"],
  [".yachts","gTLD","Generisch (weltweit registrierbar)"],
  [".yahoo","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".yamaxun","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".yandex","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".ye","ccTLD","Jemen"],
  [".yodobashi","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".yoga","gTLD","Generisch (weltweit registrierbar)"],
  [".yokohama","ccTLD","Yokohama (Japan)"],
  [".you","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".youtube","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".yt","ccTLD","Mayotte"],
  [".yun","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".za","ccTLD","Südafrika"],
  [".zappos","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".zara","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".zero","gTLD","Generisch (weltweit registrierbar)"],
  [".zip","gTLD","Generisch (weltweit registrierbar)"],
  [".zm","ccTLD","Sambia"],
  [".zone","gTLD","Generisch (weltweit registrierbar)"],
  [".zuerich","Brand","Marken-TLD (nicht öffentlich registrierbar)"],
  [".zw","ccTLD","Simbabwe"],
];

const categories = [
  { name: "😤 Reaktionen", color: "#ff6666", bg: "#2a1010", tlds: [
    { tld: ".wtf", beispiel: "was.wtf", bedeutung: "Was zur Hölle?", preise: { "prepaid-host.com": "60,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".fail", beispiel: "epic.fail", bedeutung: "Totales Versagen", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".sucks", beispiel: "montag.sucks", bedeutung: "Das nervt", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".lol", beispiel: "das.lol", bedeutung: "Zum Lachen", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".wtf", beispiel: "seriously.wtf", bedeutung: "Im Ernst jetzt?", preise: { "prepaid-host.com": "60,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
  ]},
  { name: "🥷 Vibes & Identität", color: "#00ee77", bg: "#0d2a18", tlds: [
    { tld: ".ninja", beispiel: "code.ninja", bedeutung: "Stiller Profi", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".guru", beispiel: "design.guru", bedeutung: "Der Experte", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".rocks", beispiel: "this.rocks", bedeutung: "Das ist krass", preise: { "prepaid-host.com": "40,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".cool", beispiel: "pretty.cool", bedeutung: "Einfach cool", preise: { "prepaid-host.com": "75,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".life", beispiel: "the.life", bedeutung: "Das Leben", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
  ]},
  { name: "🍕 Essen & Trinken", color: "#ffbb33", bg: "#281800", tlds: [
    { tld: ".pizza", beispiel: "best.pizza", bedeutung: "Selbsterklärend", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".coffee", beispiel: "morning.coffee", bedeutung: "Kaffee-Kult", preise: { "prepaid-host.com": "72,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".beer", beispiel: "cold.beer", bedeutung: "Hopfen & Malz", preise: { "prepaid-host.com": "40,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".wine", beispiel: "fine.wine", bedeutung: "Edler Tropfen", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".pub", beispiel: "local.pub", bedeutung: "Die Stammkneipe", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
  ]},
  { name: "🐾 Tiere", color: "#cc88ff", bg: "#1e1030", tlds: [
    { tld: ".dog", beispiel: "good.dog", bedeutung: "Guter Junge!", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".cat", beispiel: "internet.cat", bedeutung: "Das Internet", preise: { "prepaid-host.com": "71,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".pet", beispiel: "my.pet", bedeutung: "Haustier-Liebe", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".fish", beispiel: "just.fish", bedeutung: "Nur Fische", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".horse", beispiel: "dark.horse", bedeutung: "Außenseiter", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
  ]},
  { name: "🎮 Tech & Games", color: "#33ddff", bg: "#081c24", tlds: [
    { tld: ".games", beispiel: "play.games", bedeutung: "Spielzeit", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".computer", beispiel: "my.computer", bedeutung: "Nostalgie pur", preise: { "prepaid-host.com": "64,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".dev", beispiel: "my.dev", bedeutung: "Für Entwickler", preise: { "prepaid-host.com": "25,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".meme", beispiel: "dank.meme", bedeutung: "Internet-Kultur", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".app", beispiel: "cool.app", bedeutung: "Mobile-First", preise: { "prepaid-host.com": "29,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
  ]},
  { name: "🎭 Absurd & Meta", color: "#ff77dd", bg: "#280028", tlds: [
    { tld: ".monster", beispiel: "cookie.monster", bedeutung: "Halloween-Vibes", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".zone", beispiel: "danger.zone", bedeutung: "🎵 Archer-Intro", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".band", beispiel: "the.band", bedeutung: "Rockstar-Energie", preise: { "prepaid-host.com": "36,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".buzz", beispiel: "create.buzz", bedeutung: "Hype erzeugen", preise: { "prepaid-host.com": "64,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".fyi", beispiel: "just.fyi", bedeutung: "Zu deiner Info", preise: { "prepaid-host.com": "17,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
  ]},
  { name: "🌍 Länder-Hacks", color: "#ffee44", bg: "#222000", tlds: [
    { tld: ".io", beispiel: "start.io", bedeutung: "Brit. Ind. Ozean (Tech-Favorit)", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".ai", beispiel: "chat.ai", bedeutung: "Anguilla (= Artificial Intelligence)", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".fm", beispiel: "syntax.fm", bedeutung: "Mikronesien (= FM-Radio)", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
    { tld: ".tv", beispiel: "watch.tv", bedeutung: "Tuvalu (= Television)", preise: { "prepaid-host.com": "44,99 €", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: { "prepaid-host.com": "https://prepaid-host.com/domain/order" } },
    { tld: ".ski", beispiel: "ciechanow.ski", bedeutung: "Slowakei (Nachname-Hack)", preise: { "prepaid-host.com": "—", "24fire.de": "—", "prepaid-hoster.de": "—" }, links: {} },
  ]},
];

const PROVIDERS = ["prepaid-host.com", "24fire.de", "prepaid-hoster.de"];
const PROVIDER_URLS = {
  "prepaid-host.com": "https://prepaid-host.com/domain/order",
  "24fire.de": "https://24fire.de/domains/",
  "prepaid-hoster.de": "https://www.prepaid-hoster.de/domains/domain-kaufen/domain-endungen.html",
};

const TYP_COLOR = { gTLD: "#33ddff", ccTLD: "#ffbb33", Brand: "#888", "Infra/sTLD": "#ff6666" };
const TYP_LABEL = { gTLD: "gTLD", ccTLD: "ccTLD", Brand: "Brand", "Infra/sTLD": "Infra" };

const ROWS_PER_PAGE = 50;

export default function CoolTLDs() {
  const [activeTab, setActiveTab] = useState("liste");
  const [activeCategory, setActiveCategory] = useState(null);
  const [hoveredRow, setHoveredRow] = useState(null);
  const [search, setSearch] = useState("");
  const [filterTyp, setFilterTyp] = useState("alle");
  const [page, setPage] = useState(0);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return allTldsData.filter(([tld, typ, land]) => {
      const matchSearch = !q || tld.includes(q) || land.toLowerCase().includes(q);
      const matchTyp = filterTyp === "alle" || typ === filterTyp;
      return matchSearch && matchTyp;
    });
  }, [search, filterTyp]);

  const totalPages = Math.ceil(filtered.length / ROWS_PER_PAGE);
  const pageData = filtered.slice(page * ROWS_PER_PAGE, (page + 1) * ROWS_PER_PAGE);

  const handleSearch = (v) => { setSearch(v); setPage(0); };
  const handleFilter = (v) => { setFilterTyp(v); setPage(0); };

  const displayed = activeCategory !== null ? [categories[activeCategory]] : categories;

  const counts = useMemo(() => {
    const c = { alle: allTldsData.length, gTLD: 0, ccTLD: 0, Brand: 0, "Infra/sTLD": 0 };
    allTldsData.forEach(([, typ]) => { if (c[typ] !== undefined) c[typ]++; });
    return c;
  }, []);

  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0a", fontFamily: "'Courier New', monospace", padding: "24px 16px", color: "#fff" }}>
      {/* Header */}
      <div style={{ textAlign: "center", marginBottom: "20px" }}>
        <div style={{ fontSize: "10px", letterSpacing: "6px", color: "#666", textTransform: "uppercase", marginBottom: "8px" }}>
          Alle TLDs der Welt · Stand 15. Juni 2026
        </div>
        <h1 style={{
          fontSize: "clamp(28px, 6vw, 48px)", fontWeight: "900", margin: 0,
          background: "linear-gradient(135deg, #ff4444, #ff8800, #ffdd00, #00ff88, #00ccff, #cc88ff)",
          WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text", lineHeight: 1.1,
        }}>Domain Map</h1>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", justifyContent: "center", marginBottom: "24px" }}>
        {[{ id: "liste", label: "🗂 Kombinationen & Preise" }, { id: "ursprung", label: `🌍 Alle ${allTldsData.length} TLDs & Ursprung` }].map((tab) => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)} style={{
            padding: "10px 20px",
            border: "1px solid #333",
            borderBottom: activeTab === tab.id ? "2px solid #fff" : "1px solid #333",
            background: activeTab === tab.id ? "#1a1a1a" : "transparent",
            color: activeTab === tab.id ? "#fff" : "#777",
            fontSize: "11px", letterSpacing: "1px", cursor: "pointer",
            fontFamily: "'Courier New', monospace",
            borderRadius: tab.id === "liste" ? "6px 0 0 6px" : "0 6px 6px 0",
          }}>{tab.label}</button>
        ))}
      </div>

      {/* TAB 1 – Kombinationen & Preise */}
      {activeTab === "liste" && (
        <>
          <div style={{ color: "#888", fontSize: "11px", textAlign: "center", marginBottom: "16px" }}>
            Preise von{" "}
            {PROVIDERS.map((p, i) => (
              <span key={p}>
                <a href={PROVIDER_URLS[p]} target="_blank" rel="noreferrer" style={{ color: "#aaa", textDecoration: "underline" }}>{p}</a>
                {i < PROVIDERS.length - 1 ? " · " : ""}
              </span>
            ))} · — = nicht gelistet
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", justifyContent: "center", marginBottom: "20px" }}>
            <button onClick={() => setActiveCategory(null)} style={{ padding: "5px 13px", borderRadius: "4px", border: `1px solid ${activeCategory === null ? "#fff" : "#333"}`, background: activeCategory === null ? "#fff" : "transparent", color: activeCategory === null ? "#000" : "#999", fontSize: "10px", letterSpacing: "2px", cursor: "pointer", fontFamily: "'Courier New', monospace" }}>ALLE</button>
            {categories.map((cat, i) => (
              <button key={i} onClick={() => setActiveCategory(activeCategory === i ? null : i)} style={{ padding: "5px 13px", borderRadius: "4px", border: `1px solid ${activeCategory === i ? cat.color : "#333"}`, background: activeCategory === i ? cat.color + "22" : "transparent", color: activeCategory === i ? cat.color : "#999", fontSize: "10px", letterSpacing: "1px", cursor: "pointer", fontFamily: "'Courier New', monospace" }}>{cat.name}</button>
            ))}
          </div>
          <div style={{ maxWidth: "1000px", margin: "0 auto", display: "flex", flexDirection: "column", gap: "20px" }}>
            {displayed.map((cat, ci) => (
              <div key={ci} style={{ border: `1px solid ${cat.color}33`, borderRadius: "8px", overflow: "hidden", background: cat.bg }}>
                <div style={{ padding: "10px 20px", borderBottom: `1px solid ${cat.color}22`, display: "flex", alignItems: "center", gap: "10px" }}>
                  <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: cat.color, boxShadow: `0 0 8px ${cat.color}`, flexShrink: 0 }} />
                  <span style={{ fontSize: "13px", fontWeight: "bold", color: cat.color, letterSpacing: "2px" }}>{cat.name}</span>
                </div>
                <div style={{ overflowX: "auto" }}>
                  <table style={{ width: "100%", borderCollapse: "collapse", minWidth: "680px" }}>
                    <thead>
                      <tr>{["TLD", "Beispiel", "Vibe", "prepaid-host.com", "24fire.de", "prepaid-hoster.de"].map((h) => (
                        <th key={h} style={{ padding: "9px 16px", textAlign: "left", fontSize: "9px", letterSpacing: "2px", color: "#777", borderBottom: "1px solid #222", fontWeight: "normal", whiteSpace: "nowrap" }}>{h.toUpperCase()}</th>
                      ))}</tr>
                    </thead>
                    <tbody>
                      {cat.tlds.map((row, ri) => {
                        const key = `${ci}-${ri}`; const isH = hoveredRow === key;
                        return (
                          <tr key={ri} onMouseEnter={() => setHoveredRow(key)} onMouseLeave={() => setHoveredRow(null)} style={{ background: isH ? cat.color + "11" : "transparent", transition: "background 0.1s", borderBottom: ri < cat.tlds.length - 1 ? "1px solid #111" : "none" }}>
                            <td style={{ padding: "11px 16px", fontWeight: "bold", color: cat.color, fontSize: "15px", letterSpacing: "1px", whiteSpace: "nowrap" }}>{row.tld}</td>
                            <td style={{ padding: "11px 16px", color: isH ? "#fff" : "#ddd", fontSize: "13px", fontStyle: "italic", transition: "color 0.1s", whiteSpace: "nowrap" }}>{row.beispiel}</td>
                            <td style={{ padding: "11px 16px", color: "#aaa", fontSize: "12px" }}>{row.bedeutung}</td>
                            {PROVIDERS.map((provider) => {
                              const preis = row.preise[provider]; const link = row.links[provider]; const hasPrice = preis && preis !== "—";
                              return (
                                <td key={provider} style={{ padding: "11px 16px", whiteSpace: "nowrap", textAlign: "center" }}>
                                  {hasPrice ? <a href={link || PROVIDER_URLS[provider]} target="_blank" rel="noreferrer" style={{ display: "inline-block", padding: "3px 10px", borderRadius: "3px", background: cat.color + "22", border: `1px solid ${cat.color}55`, color: cat.color, fontSize: "12px", fontWeight: "bold", textDecoration: "none" }}>{preis}</a>
                                    : <span style={{ color: "#555", fontSize: "13px" }}>—</span>}
                                </td>
                              );
                            })}
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </div>
          <div style={{ textAlign: "center", marginTop: "24px", color: "#444", fontSize: "10px", letterSpacing: "2px", lineHeight: 2 }}>
            PREISE VON PREPAID-HOST.COM (JUNI 2026, INKL. 19% MWST.) · — = NICHT GELISTET ODER NICHT ABRUFBAR
          </div>
        </>
      )}

      {/* TAB 2 – Alle TLDs */}
      {activeTab === "ursprung" && (
        <div style={{ maxWidth: "900px", margin: "0 auto" }}>
          {/* Controls */}
          <div style={{ display: "flex", gap: "10px", marginBottom: "16px", flexWrap: "wrap", alignItems: "center" }}>
            <input type="text" placeholder="TLD oder Land suchen..." value={search} onChange={(e) => handleSearch(e.target.value)}
              style={{ flex: 1, minWidth: "160px", padding: "8px 14px", background: "#141414", border: "1px solid #333", borderRadius: "4px", color: "#eee", fontSize: "12px", fontFamily: "'Courier New', monospace", outline: "none" }} />
            {[["alle", "Alle"], ["gTLD", "gTLD"], ["ccTLD", "ccTLD"], ["Brand", "Brand"]].map(([key, label]) => (
              <button key={key} onClick={() => handleFilter(key)} style={{
                padding: "8px 14px", borderRadius: "4px",
                border: `1px solid ${filterTyp === key ? (TYP_COLOR[key] || "#fff") : "#333"}`,
                background: filterTyp === key ? "#1e1e1e" : "transparent",
                color: filterTyp === key ? (TYP_COLOR[key] || "#fff") : "#777",
                fontSize: "10px", letterSpacing: "1px", cursor: "pointer", fontFamily: "'Courier New', monospace", whiteSpace: "nowrap",
              }}>{label} <span style={{ opacity: 0.6 }}>({counts[key] ?? filtered.length})</span></button>
            ))}
          </div>

          {/* Stats */}
          <div style={{ display: "flex", gap: "16px", marginBottom: "16px", flexWrap: "wrap" }}>
            {[["gTLD", "Generisch (öffentlich)"], ["ccTLD", "Länderspezifisch"], ["Brand", "Marken (gesperrt)"]].map(([typ, label]) => (
              <div key={typ} style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                <div style={{ width: "10px", height: "10px", borderRadius: "2px", background: TYP_COLOR[typ] }} />
                <span style={{ color: "#888", fontSize: "11px" }}><span style={{ color: TYP_COLOR[typ] }}>{typ}</span> — {label}</span>
              </div>
            ))}
          </div>

          {/* Result count + pagination info */}
          <div style={{ color: "#555", fontSize: "11px", marginBottom: "12px", display: "flex", justifyContent: "space-between", flexWrap: "wrap", gap: "8px" }}>
            <span>{filtered.length} TLDs · Seite {page + 1} von {totalPages}</span>
            <span style={{ color: "#444" }}>50 pro Seite</span>
          </div>

          {/* Table */}
          <div style={{ border: "1px solid #1e1e1e", borderRadius: "8px", overflow: "hidden", background: "#111" }}>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ background: "#161616" }}>
                  {["#", "TLD", "Typ", "Land / Ursprung"].map((h) => (
                    <th key={h} style={{ padding: "10px 16px", textAlign: "left", fontSize: "9px", letterSpacing: "3px", color: "#666", borderBottom: "1px solid #222", fontWeight: "normal" }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {pageData.map(([tld, typ, land], i) => {
                  const color = TYP_COLOR[typ] || "#888";
                  const globalIdx = page * ROWS_PER_PAGE + i + 1;
                  return (
                    <tr key={i} style={{ borderBottom: i < pageData.length - 1 ? "1px solid #161616" : "none" }}
                      onMouseEnter={(e) => e.currentTarget.style.background = "#181818"}
                      onMouseLeave={(e) => e.currentTarget.style.background = "transparent"}>
                      <td style={{ padding: "10px 16px", color: "#333", fontSize: "11px", width: "48px" }}>{globalIdx}</td>
                      <td style={{ padding: "10px 16px", fontWeight: "bold", color, fontSize: "15px", letterSpacing: "0.5px", whiteSpace: "nowrap" }}>{tld}</td>
                      <td style={{ padding: "10px 16px", whiteSpace: "nowrap" }}>
                        <span style={{ display: "inline-block", padding: "2px 7px", borderRadius: "3px", fontSize: "9px", letterSpacing: "1px", fontWeight: "bold", background: color + "18", border: `1px solid ${color}33`, color }}>{TYP_LABEL[typ] || typ}</span>
                      </td>
                      <td style={{ padding: "10px 16px", color: "#ccc", fontSize: "12px" }}>{land}</td>
                    </tr>
                  );
                })}
                {pageData.length === 0 && (
                  <tr><td colSpan={4} style={{ padding: "32px", textAlign: "center", color: "#444", fontSize: "13px" }}>Keine TLDs gefunden</td></tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div style={{ display: "flex", justifyContent: "center", gap: "8px", marginTop: "16px", flexWrap: "wrap" }}>
              <button onClick={() => setPage(0)} disabled={page === 0} style={{ padding: "6px 12px", background: "transparent", border: "1px solid #333", borderRadius: "4px", color: page === 0 ? "#333" : "#888", cursor: page === 0 ? "default" : "pointer", fontFamily: "'Courier New', monospace", fontSize: "11px" }}>«</button>
              <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0} style={{ padding: "6px 12px", background: "transparent", border: "1px solid #333", borderRadius: "4px", color: page === 0 ? "#333" : "#888", cursor: page === 0 ? "default" : "pointer", fontFamily: "'Courier New', monospace", fontSize: "11px" }}>‹</button>
              {Array.from({ length: Math.min(7, totalPages) }, (_, i) => {
                let p;
                if (totalPages <= 7) p = i;
                else if (page < 4) p = i;
                else if (page > totalPages - 5) p = totalPages - 7 + i;
                else p = page - 3 + i;
                return (
                  <button key={p} onClick={() => setPage(p)} style={{ padding: "6px 12px", background: p === page ? "#fff" : "transparent", border: `1px solid ${p === page ? "#fff" : "#333"}`, borderRadius: "4px", color: p === page ? "#000" : "#888", cursor: "pointer", fontFamily: "'Courier New', monospace", fontSize: "11px", minWidth: "36px" }}>{p + 1}</button>
                );
              })}
              <button onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))} disabled={page === totalPages - 1} style={{ padding: "6px 12px", background: "transparent", border: "1px solid #333", borderRadius: "4px", color: page === totalPages - 1 ? "#333" : "#888", cursor: page === totalPages - 1 ? "default" : "pointer", fontFamily: "'Courier New', monospace", fontSize: "11px" }}>›</button>
              <button onClick={() => setPage(totalPages - 1)} disabled={page === totalPages - 1} style={{ padding: "6px 12px", background: "transparent", border: "1px solid #333", borderRadius: "4px", color: page === totalPages - 1 ? "#333" : "#888", cursor: page === totalPages - 1 ? "default" : "pointer", fontFamily: "'Courier New', monospace", fontSize: "11px" }}>»</button>
            </div>
          )}

          <div style={{ marginTop: "20px", color: "#333", fontSize: "10px", textAlign: "center", letterSpacing: "1px", lineHeight: 2 }}>
            QUELLE: IANA ROOT ZONE DATABASE · STAND 15. JUNI 2026 · 1286 TLDS (OHNE IDN/PUNYCODE XN--)
          </div>
        </div>
      )}
    </div>
  );
}
